version: '2'
services:
    mongo:
        image: docker.finogeeks.club/base/mongo:3.6
    go-gin:
        image: docker.finogeeks.club/finochat/go-gin
        tty: true
        ports:
            - 9999:9999
            - 8080:8080
        environment:
          - "mongoDomain=mongo"

